instance_groups: []
name: compile-releases
releases:
- name: concourse
  sha1: b14cebd078c98840177a1c73c27b19f2f8933c23
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.13.1
  version: 3.13.1
- name: os-conf
  sha1: 78d79f08ff5001cc2a24f572837c7a9c59a0e796
  url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=18
  version: 18
- name: credhub-importer
  sha1: a945710d1d7d3dfb8f8e117aa6f81e2fb5c70709
  url: https://github.com/cloudfoundry-community/credhub-importer-boshrelease/releases/download/1/credhub-importer-1.tgz
  version: 1
- name: postgres
  sha1: 86a1333122e9cdd051551c83ec26d36f6e325d6c
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=22
  version: 22
- name: bucc-bbr
  url: git+https://github.com/starkandwayne/bucc-bbr-boshrelease
  version: 6
stemcells:
- alias: large
  os: ubuntu-trusty
  version: "3541.10"
update:
  canaries: 1
  canary_watch_time: 1000 - 90000
  max_in_flight: 1
  update_watch_time: 1000 - 90000
